// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: messages.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMessage = `-- name: CreateMessage :one
insert into messages(
    id, description, sender_id, reciever_id,
    group_id, sent, created_at, updated_at
)
values(
    gen_random_uuid(),
    $1, $2, $3, $4, $5, NOW(), NOW()
)
returning id, description, sender_id, reciever_id, group_id, sent, recieved, created_at, updated_at
`

type CreateMessageParams struct {
	Description string
	SenderID    uuid.UUID
	RecieverID  uuid.NullUUID
	GroupID     uuid.NullUUID
	Sent        bool
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.Description,
		arg.SenderID,
		arg.RecieverID,
		arg.GroupID,
		arg.Sent,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Description,
		&i.SenderID,
		&i.RecieverID,
		&i.GroupID,
		&i.Sent,
		&i.Recieved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllGroupMessages = `-- name: GetAllGroupMessages :many
select id, description, sender_id, reciever_id, group_id, sent, recieved, created_at, updated_at from messages where group_id = $1 and created_at < $2 order by created_at limit 10
`

type GetAllGroupMessagesParams struct {
	GroupID   uuid.NullUUID
	CreatedAt time.Time
}

func (q *Queries) GetAllGroupMessages(ctx context.Context, arg GetAllGroupMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getAllGroupMessages, arg.GroupID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.SenderID,
			&i.RecieverID,
			&i.GroupID,
			&i.Sent,
			&i.Recieved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMessages = `-- name: GetAllMessages :many
select id, description, sender_id, reciever_id, group_id, sent, recieved, created_at, updated_at from messages where sender_id = $1 and reciever_id = $2 and created_at < $3 order by created_at limit 10
`

type GetAllMessagesParams struct {
	SenderID   uuid.UUID
	RecieverID uuid.NullUUID
	CreatedAt  time.Time
}

func (q *Queries) GetAllMessages(ctx context.Context, arg GetAllMessagesParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getAllMessages, arg.SenderID, arg.RecieverID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.SenderID,
			&i.RecieverID,
			&i.GroupID,
			&i.Sent,
			&i.Recieved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestGroupMessagesByGroupID = `-- name: GetLatestGroupMessagesByGroupID :many
select groups.name as group_name, messages.description as messages, count(*) as total_new_messages
from messages join groups on messages.group_id = groups.id where messages.created_at > $1 group by group_name
order by messages.created_at
`

type GetLatestGroupMessagesByGroupIDRow struct {
	GroupName        string
	Messages         string
	TotalNewMessages int64
}

func (q *Queries) GetLatestGroupMessagesByGroupID(ctx context.Context, createdAt time.Time) ([]GetLatestGroupMessagesByGroupIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestGroupMessagesByGroupID, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestGroupMessagesByGroupIDRow
	for rows.Next() {
		var i GetLatestGroupMessagesByGroupIDRow
		if err := rows.Scan(&i.GroupName, &i.Messages, &i.TotalNewMessages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestMessagesByRecieverID = `-- name: GetLatestMessagesByRecieverID :many
select users.username as sender, messages.description as messages, count(*) as total_new_messages
from messages join users on messages.sender_id = users.id where messages.reciever_id = $1 and
messages.created_at > $2 group by users.username order by messages.created_at
`

type GetLatestMessagesByRecieverIDParams struct {
	RecieverID uuid.NullUUID
	CreatedAt  time.Time
}

type GetLatestMessagesByRecieverIDRow struct {
	Sender           string
	Messages         string
	TotalNewMessages int64
}

func (q *Queries) GetLatestMessagesByRecieverID(ctx context.Context, arg GetLatestMessagesByRecieverIDParams) ([]GetLatestMessagesByRecieverIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestMessagesByRecieverID, arg.RecieverID, arg.CreatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesByRecieverIDRow
	for rows.Next() {
		var i GetLatestMessagesByRecieverIDRow
		if err := rows.Scan(&i.Sender, &i.Messages, &i.TotalNewMessages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markGroupMessageRead = `-- name: MarkGroupMessageRead :exec
insert into groupmessage_groupmembers(message_id, group_member_id, group_id, created_at)
values($1, $2, $3, NOW())
`

type MarkGroupMessageReadParams struct {
	MessageID     uuid.UUID
	GroupMemberID uuid.UUID
	GroupID       uuid.UUID
}

func (q *Queries) MarkGroupMessageRead(ctx context.Context, arg MarkGroupMessageReadParams) error {
	_, err := q.db.ExecContext(ctx, markGroupMessageRead, arg.MessageID, arg.GroupMemberID, arg.GroupID)
	return err
}

const markMessageReceived = `-- name: MarkMessageReceived :one
update messages set received = true where id = $1 and reciever_id = $2 and sender_id = $3
returning updated_at
`

type MarkMessageReceivedParams struct {
	ID         uuid.UUID
	RecieverID uuid.NullUUID
	SenderID   uuid.UUID
}

func (q *Queries) MarkMessageReceived(ctx context.Context, arg MarkMessageReceivedParams) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, markMessageReceived, arg.ID, arg.RecieverID, arg.SenderID)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}

const removeMessage = `-- name: RemoveMessage :one
delete from messages where id = $1 and sender_id = $2 and reciever_id = $3 and group_id = $4
returning sender_id, group_id
`

type RemoveMessageParams struct {
	ID         uuid.UUID
	SenderID   uuid.UUID
	RecieverID uuid.NullUUID
	GroupID    uuid.NullUUID
}

type RemoveMessageRow struct {
	SenderID uuid.UUID
	GroupID  uuid.NullUUID
}

func (q *Queries) RemoveMessage(ctx context.Context, arg RemoveMessageParams) (RemoveMessageRow, error) {
	row := q.db.QueryRowContext(ctx, removeMessage,
		arg.ID,
		arg.SenderID,
		arg.RecieverID,
		arg.GroupID,
	)
	var i RemoveMessageRow
	err := row.Scan(&i.SenderID, &i.GroupID)
	return i, err
}

const updateMessage = `-- name: UpdateMessage :one
update messages set description = $1, updated_at = NOW() where id = $2 and sender_id = $3 and group_id = $4
returning description, sender_id, reciever_id, group_id, sent, recieved, created_at, updated_at
`

type UpdateMessageParams struct {
	Description string
	ID          uuid.UUID
	SenderID    uuid.UUID
	GroupID     uuid.NullUUID
}

type UpdateMessageRow struct {
	Description string
	SenderID    uuid.UUID
	RecieverID  uuid.NullUUID
	GroupID     uuid.NullUUID
	Sent        bool
	Recieved    bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) (UpdateMessageRow, error) {
	row := q.db.QueryRowContext(ctx, updateMessage,
		arg.Description,
		arg.ID,
		arg.SenderID,
		arg.GroupID,
	)
	var i UpdateMessageRow
	err := row.Scan(
		&i.Description,
		&i.SenderID,
		&i.RecieverID,
		&i.GroupID,
		&i.Sent,
		&i.Recieved,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
