// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Group struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GroupAdmin struct {
	GroupID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type GroupMessageRead struct {
	MessageID     uuid.UUID
	GroupMemberID uuid.UUID
	GroupID       uuid.UUID
	CreatedAt     time.Time
}

type GroupMessageReceived struct {
	MessageID     uuid.UUID
	GroupMemberID uuid.UUID
	GroupID       uuid.UUID
	ReceivedAt    time.Time
}

type GroupMessageReceiver struct {
	MessageID      uuid.UUID
	MemberID       uuid.UUID
	GroupID        uuid.UUID
	IsAllowedToSee bool
}

type Message struct {
	ID                     uuid.UUID
	Description            string
	SenderID               uuid.UUID
	RecieverID             uuid.NullUUID
	GroupID                uuid.NullUUID
	Sent                   bool
	Recieved               bool
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Read                   bool
	IsSenderAllowedToSee   bool
	IsReceiverAllowedToSee bool
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

type User struct {
	ID            uuid.UUID
	Phonenumber   string
	Username      string
	Password      string
	LastAvailable sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type UsersGroup struct {
	UserID    uuid.UUID
	GroupID   uuid.UUID
	CreatedAt time.Time
}
